### ISSUE TITLE
Herobrine dimension issue

### ISSUE THREAD

**Issue by Peluchomp** [miyo6032/MaelstromMod#13]
In the herobrine dimension (dont know its name) you are constantly being pulled in to an especific direction. Is it a bug or is it made on purpose?

**Comment by miyo6032** [comment]
Yes, that effect is on purpose. The idea is to emulate a strong wind. If you don't mind me asking, is there a reason why you thought it was a bug?

**Comment by Peluchomp** [comment]
Yes, I had the particles at minimal now it looks like there is wind. Maybe adding a sound may help people that have minimal or disabled particles don't think its buggy.

**Comment by miyo6032** [comment]
That is a good suggestion. Thanks for bringing it up. I'll put this in my backlog.
