### ISSUE TITLE
Weird visual of the fog in the canyon dimension

### ISSUE THREAD

**Issue by Zack7292** [miyo6032/MaelstromMod#14]
**Describe the bug**
when you getting high in the canyon dimension and look down. the fog is look weirdly black
here a screen https://imgur.com/mXv3AMV

**To Reproduce**
just go in the canyon dimension, get high (around the top of the canion) and look down

**Forge Version and Maelstrom Mod Version**
forge: 1.12.2 - 14.23.5.2847
maelstrom: 0.3.2

**Comment by miyo6032** [comment]
Thanks for pointing that out. I will add that to the patch.

**Comment by Zack7292** [comment]
:)
