### ISSUE TITLE
Massive framerate drops caused by particles.

### ISSUE THREAD

**Issue by Maowcraft** [miyo6032/MaelstromMod#17]
**Describe the bug**
Large amounts of framerate drops occur when in the proximity of the Maelstrom tower, or in the Fracture dimension near the Maelstrom castle thing, they stop happening when particles are turned down to Minimal.

**To Reproduce**
1. Wait for the Maelstrom tower to spawn
2. Turn particles up to All

**Forge Version and Maelstrom Mod Version**
Forge: 14.23.5.2847
Maelstrom Mod: 1.12.2-0.3.3

**Comment by miyo6032** [comment]
I was unable to replicate this. In general, I'm confused about why setting particles to minimal works because none of the particles can be disabled under any setting. Did you have any additional mods installed? It could be some sort of conflict.

**Comment by miyo6032** [comment]
Closing this issue because it's been a week and I haven't gotten a response.
