### ISSUE TITLE
Translation of Mod Korean Version

### ISSUE THREAD

**Issue by jason9727** [miyo6032/MaelstromMod#22]
I'm a Korean fan of this mod.
So I translated this mod into Korean.
I hope this translation will be applied to the next version. :)
Here's the file.
Since .jar file is not supported, we are forced to upload it as .zip file.
[mm_kr.zip](https://github.com/miyo6032/MaelstromMod/files/4602963/mm_kr.zip)
(I'm sorry if my English was weird because I used a translator.)

**Comment by miyo6032** [comment]
Thanks! I will add it in if I can.

**Comment by Garam1207** [comment]
Are you alive?
