### ISSUE TITLE
[0.4.1-Snapshot.3]Ticking Entity Crash when Champion collides with BoP grass??

### ISSUE THREAD

**Issue by SandwichHorror** [miyo6032/MaelstromMod#26]
**Describe the bug**
When Champion performs his leap-smash in a BoP biome, he frequently causes a ticking entity crash.

Crash report here: https://gist.github.com/SandwichHorror/79cb79b901aff02bfdaecda760487edb

**To Reproduce**
Get the Champion to fight another mob in a Biomes o' Plenty biome.

**Forge Version and Maelstrom Mod Version**
Latest 1.12 Forge; 0.4.1-snapshot.3

**Comment by miyo6032** [comment]
Alright, I saw this after I made some changes to the leaping. I have reason to believe I fixed this error for the next snapshot, but I'm not 100% sure. I will leave this open for a little bit afterward just in case it does come up again after snapshot 4.
