### ISSUE TITLE
game crash when me and my friends enters the dimension dark nexus

### ISSUE THREAD

**Issue by Flipper19** [miyo6032/MaelstromMod#27]
[crash-2020-09-27_19.41.17-client.txt](https://github.com/miyo6032/MaelstromMod/files/5289220/crash-2020-09-27_19.41.17-client.txt)

Hello, I dont know much about modding but, me and my friends really want to play this, can u help me out?

**Comment by miyo6032** [comment]
Sorry for the late response! I think you came across a bug - it will be fixed in the next update. Or if you don't want to wait that long, in the next snapshot (Snapshot-5) although the snapshots are much less stable. But you can look for the next snapshot on this website under releases.

**Comment by Flipper19** [comment]
thank you

**Comment by Flipper19** [comment]
there is a date for a snapshot? :v

**Comment by miyo6032** [comment]
Working on some big changes, so probably a week or two. I'll keep you informed.

**Comment by miyo6032** [comment]
Note that this is unstable, so there might be other problems, but the crash you experienced should be fixed.
https://github.com/miyo6032/MaelstromMod/releases/tag/0.4.1-snapshot.5
