### ISSUE TITLE
Maelstrom dosent work with my modpack

### ISSUE THREAD

**Issue by TerraCrafterMC** [miyo6032/MaelstromMod#29]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2020-10-31 11:49:52 CDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Maelstrom Mod (mm)
Caused by: java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.beast.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.beast.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.beast
    at net.minecraft.stats.StatBase.registerStat(SourceFile:41)
    at net.minecraft.stats.StatList.getStatKillEntity(StatList.java:305)
    at net.minecraft.entity.EntityList$EntityEggInfo.<init>(EntityList.java:450)
    at net.minecraftforge.fml.common.registry.EntityRegistry.registerEgg(EntityRegistry.java:242)
    at net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(EntityRegistry.java:193)
    at com.barribob.MaelstromMod.init.ModEntities.registerEntityWithID(ModEntities.java:278)
    at com.barribob.MaelstromMod.init.ModEntities.registerEntities(ModEntities.java:180)
    at com.barribob.MaelstromMod.Main.PreInit(Main.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 433099192 bytes (413 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 132 mods loaded, 131 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version             | Source                                             | Signature                                |
       |:----- |:-------------------- |:------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft            | 1.12.2              | minecraft.jar                                      | None                                     |
       | LCH   | mcp                  | 9.42                | minecraft.jar                                      | None                                     |
       | LCH   | FML                  | 8.0.99.99           | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCH   | forge                | 14.23.5.2847        | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCH   | openmodscore         | 0.12.2              | minecraft.jar                                      | None                                     |
       | LCH   | foamfixcore          | 7.7.4               | minecraft.jar                                      | None                                     |
       | LCH   | damageindicatorsmod  | 1.0                 | [1.12.2]DamageIndicatorsMod-3.5.1.jar              | None                                     |
       | LCH   | jei                  | 4.15.0.268          | jei_1.12.2-4.15.0.268.jar                          | None                                     |
       | LCH   | abyssalcraft         | 1.9.19.1            | AbyssalCraft-1.12.2-1.9.19.1.jar                   | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCH   | abyssaldepths        | 1.12.2-0.3.1        | AbyssalDepths-1.12.2-0.3.1.jar                     | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
       | LCH   | fastbench            | 1.7.2               | FastWorkbench-1.12.2-1.7.2.jar                     | None                                     |
       | LCH   | actuallyadditions    | 1.12.2-r151         | ActuallyAdditions-1.12.2-r151-2.jar                | None                                     |
       | LCH   | baubles              | 1.5.2               | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCH   | actuallybaubles      | 1.1                 | ActuallyBaubles-1.12-1.1.jar                       | None                                     |
       | LCH   | aether_legacy        | 1.4.4               | aether_legacy-1.12.2-v1.4.4.jar                    | None                                     |
       | LCH   | kagic                | X11p13              | kagic-X11p13.jar                                   | None                                     |
       | LCH   | allthesingleladies   | 1.6                 | allthesingleladies-1.6.jar                         | None                                     |
       | LCH   | animalbikes          | 1.11.2              | AnimalBikes_1.12.2(13Jan19).jar                    | None                                     |
       | LCH   | artisans_tabs        | 1.3.0.3             | Artisan's+Tabs+-+v-1.12.2-1.3.0.3.jar              | None                                     |
       | LCH   | atum                 | 2.0.17              | Atum-1.12.2-2.0.17.jar                             | None                                     |
       | LCH   | autoreglib           | 1.3-32              | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCH   | codechickenlib       | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | avaritia             | 3.3.0               | Avaritia-1.12.2-3.3.0.33-universal.jar             | None                                     |
       | LCH   | thaumcraft           | 6.1.BETA26          | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
       | LCH   | botania              | r1.10-363           | Botania+r1.10-363.jar                              | None                                     |
       | LCH   | avaritiatweaks       | @VERSION@           | Avaritia's+Complement-1.12.2-1.2a.jar              | None                                     |
       | LCH   | battletowers         | 1.6.5               | BattleTowers-1.12.2.jar                            | None                                     |
       | LCH   | blocklings           | 1.0                 | Blocklings+6.0.1_b+-+1.12.2.jar                    | None                                     |
       | LCH   | bookshelf            | 2.3.590             | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | redstoneflux         | 2.1.1               | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
       | LCH   | brandonscore         | 2.4.18              | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
       | LCH   | crafttweaker         | 4.1.20              | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
       | LCH   | cfm                  | 6.3.0               | cfm-6.3.0-mc1.12.2.jar                             | None                                     |
       | LCH   | chancecubes          | 1.12.2-5.0.2.345    | ChanceCubes-1.12.2-5.0.2.345.jar                   | None                                     |
       | LCH   | chickens             | 6.1.0               | chickens-6.1.0.jar                                 | None                                     |
       | LCH   | ctm                  | MC1.12.2-1.0.2.31   | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
       | LCH   | chisel               | MC1.12.2-1.0.2.45   | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
       | LCH   | chunkanimator        | 1.2                 | ChunkAnimator-MC1.12-1.2.jar                       | None                                     |
       | LCH   | clumps               | 3.1.2               | Clumps-3.1.2.jar                                   | None                                     |
       | LCH   | cyclopscore          | 1.6.1               | CyclopsCore-1.12.2-1.6.1.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | colossalchests       | 1.7.3               | ColossalChests-1.12.2-1.7.3.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | craftablehorsearmour | 1.3                 | CraftableHorseArmour-1.3.0-1.12.jar                | None                                     |
       | LCH   | ctgui                | 1.0.0               | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
       | LCH   | crafttweakerjei      | 2.0.3               | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
       | LCH   | customnpcs           | 1.12                | CustomNPCs_1.12.2-(01Oct19).jar                    | None                                     |
       | LCH   | cxlibrary            | 1.6.1               | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
       | LCH   | deathquotes          | 1.2.0               | DeathQuotes-1.2.0-mc1.12-forge.jar                 | None                                     |
       | LCH   | defiledlands         | 1.4.3               | defiledlands-1.12.2-1.4.3.jar                      | None                                     |
       | LCH   | derpcats             | 1.9.3               | derpcats-1.9.3.jar                                 | None                                     |
       | LCH   | doge                 | 0.6.0               | DogeMod-1.12.2-0.6.0.jar                           | None                                     |
       | LCH   | dldungeonsjbg        | 1.12.10             | DoomlikeDungeons-1.12.10-MC1.12.2.jar              | None                                     |
       | LCH   | draconicevolution    | 2.3.25              | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
       | LCH   | dragonmounts         | 1.12.2-1.6.3        | DragonMounts2-1.12.2-1.6.3.jar                     | None                                     |
       | LCH   | engender_companion   | V0.3PA              | Engender+Companion+V0.3PA+1.12.2.jar               | None                                     |
       | LCH   | ageofabyssalcraft    | 0.7                 | Engender+Mod-1.12.2-0.7-pre1.jar                   | None                                     |
       | LCH   | ageofchaos           | 0.7                 | Engender+Mod-1.12.2-0.7-pre1.jar                   | None                                     |
       | LCH   | ageofminecraft       | 0.7                 | Engender+Mod-1.12.2-0.7-pre1.jar                   | None                                     |
       | LCH   | erebus               | 1.0.31              | Erebus-1.0.31.jar                                  | None                                     |
       | LCH   | evep                 | 1.5.1               | evep-1.5.1.jar                                     | None                                     |
       | LCH   | extrautils2          | 1.0                 | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | LCH   | fcl                  | 1.XII.54            | Fexcraft+Common+Library-1.XII.54.jar               | None                                     |
       | LCH   | famm                 | 3.3.0               | FAMM-3.3.0.jar                                     | None                                     |
       | LCH   | farlanders           | 1.0.1               | farlanders-1.12.2-1.0.1.jar                        | None                                     |
       | LCH   | fastfurnace          | 1.3.1               | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
       | LCH   | tmt                  | 1.8                 | Fexcraft+Common+Library-1.XII.54.jar               | None                                     |
       | LCH   | foamfix              | 0.10.10-1.12.2      | foamfix-0.10.10-1.12.2.jar                         | None                                     |
       | LCH   | forgelin             | 1.8.4               | Forgelin-1.8.4.jar                                 | None                                     |
       | LCH   | futureminecraf       | 1.3.0.2             | FutureVersions+v1.3.0.2.jar                        | None                                     |
       | LCH   | gargoyles            | 1                   | Gargoyles+mod+1.12.2+patch+1.jar                   | None                                     |
       | LCH   | uteamcore            | 2.2.5.147           | u_team_core-1.12.2-2.2.5.147.jar                   | None                                     |
       | LCH   | halloween_luckyblock | 2.2.2.8             | halloween_luckyblock-1.12.2-2.2.2.8.jar            | None                                     |
       | LCH   | headcrumbs           | 2.0.4               | Headcrumbs-1.12.2-2.0.5.17.jar                     | None                                     |
       | LCH   | heroicarmory         | 1.1.3               | heroicarmory-1.2.0.jar                             | None                                     |
       | LCH   | hunterillager        | 1.2                 | hunterillager-1.12.2-1.2.jar                       | None                                     |
       | LCH   | huntingdim           | 1.0.42              | HuntingDimension-1.12.2-1.0.42.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | icbmclassic          | 1.12.2-3.3.0.63     | ICBM-classic-1.12.2-3.3.0b63.jar                   | None                                     |
       | LCH   | ichunutil            | 7.2.2               | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | illagers_plus        | 1.1                 | IllagersPlus-1.12.2-1.1.3.jar                      | None                                     |
       | LCH   | yba                  | 1.0                 | Implements+of+Extinction+v1.1B-1.12.2.jar          | None                                     |
       | LCH   | imsm                 | 1.12                | Instant-Massive-Structures-Mod-1.12.2.jar          | None                                     |
       | LCH   | inventorypets        | 2.0.5               | inventorypets-1.12-2.0.5.jar                       | None                                     |
       | LCH   | ironchest            | 1.12.2-7.0.67.844   | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LCH   | jmr                  | 1.6                 | John+Mod+Resurrected+1.6-1.12.2.jar                | None                                     |
       | LCH   | journeymap           | 1.12.2-5.5.5        | journeymap-1.12.2-5.5.5.jar                        | None                                     |
       | LCH   | jeid                 | 1.0.3-55            | JustEnoughIDs-1.0.3-55.jar                         | None                                     |
       | LCH   | jeresources          | 0.9.2.60            | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
       | LCH   | libraryex            | 1.1.3               | LibraryEx-1.12.2-1.1.3.jar                         | None                                     |
       | LCH   | lootbags             | 2.5.8.5             | LootBags-1.12.2-2.5.8.5.jar                        | None                                     |
       | LCH   | lootoverhaul         | 1.2                 | LootOverhaul-1.2.jar                               | None                                     |
       | LCH   | lost_aether          | 1.0.1               | lost-aether-content-1.12.2-1.0.1.jar               | None                                     |
       | LCH   | lucky                | 7.6.0               | Lucky-Block-Mod-1.12.2.zip                         | None                                     |
       | LCH   | lycanitesmobs        | 2.0.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.0.0.jar                   | None                                     |
       | LCE   | mm                   | 0.4                 | Maelstrom+Mod-0.4.jar                              | None                                     |
       | LC    | mclib                | 1.0.4               | mclib-1.0.4-1.12.2.jar                             | None                                     |
       | LC    | memeinabottle        | 2.1.1               | MemeInABottle-1.12.X-2.1.1.jar                     | None                                     |
       | LC    | metamorph            | 1.1.10              | metamorph-1.1.10-1.12.2.jar                        | None                                     |
       | LC    | mightyenderchicken   | 7.3.0               | MightyEnderChicken-1.12.2-7.3.0.jar                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LC    | mocreatures          | 12.0.5              | Mo-Creatures-Mod-1.12.2.jar                        | None                                     |
       | LC    | mobbattle            | 2.3.3               | MobBattleMod-1.12.2-2.3.3.jar                      | None                                     |
       | LC    | moreexplosives       | 1.0.2               | More+Explosives+V1.0.2.jar                         | None                                     |
       | LC    | morefurnaces         | 1.10.5              | morechickens-1.12.2-3.1.0.jar                      | None                                     |
       | LC    | llibrary             | 1.7.19              | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LC    | mowziesmobs          | 1.5.4               | mowziesmobs-1.5.4.jar                              | None                                     |
       | LC    | multimob             | 1.0.5               | multimob-1.0.5.jar                                 | None                                     |
       | LC    | mutantmobs           | 1.0.1               | Mutant+Mobs+V1.0.1.jar                             | None                                     |
       | LC    | mutantbeasts         | 1.12.2-0.7.1        | MutantBeasts-1.12.2-0.7.1.jar                      | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
       | LC    | naturescompass       | 1.8.3               | mysticalworld-1.12.2-1.7.1.jar                     | None                                     |
       | LC    | netherex             | 2.1.7               | NetherEx-1.12.2-2.1.7.jar                          | None                                     |
       | LC    | nikkorimod           | 1.7.1               | NikkoriMOD_ver-1.7.1.jar                           | None                                     |
       | LC    | theoffhandedgamers   | 1.0.1               | OffhandedGamers_1.12.2_v1.0.1.jar                  | None                                     |
       | LC    | openmods             | 0.12.2              | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LC    | openblocks           | 1.8.1               | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LC    | harvestcraft         | 1.12.2zb            | p455w0rdslib-1.12.2-2.2.156.jar                    | None                                     |
       | LC    | performant           | 1.12.2-1.4          | performant-1.12.2-1.10.jar                         | None                                     |
       | LC    | potioncore           | 1.9_for_1.12.2      | PotionCore-1.9_for_1.12.2.jar                      | None                                     |
       | LC    | prefab               | 1.3.0.26            | prefab-1.3.0.26.jar                                | None                                     |
       | LC    | primitivemobs        | 1.2.3a              | primitivemobs-1.2.3a.jar                           | None                                     |
       | LC    | specialmobs          | 1.0.2_for_mc1.12.2  | specialmobs-1.0.2_for_mc1.12.2.jar                 | None                                     |
       | LC    | supertnt             | 1.0.1               | Super-TNT-Mod-1.12.2.jar                           | None                                     |
       | LC    | surge                | 2.0.77              | Surge-1.12.2-2.0.77.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | iiz_tntmod_4.1       | 4.1                 | TNT Mod v4.1 MC 1.12.2.jar                         | None                                     |
       | LC    | uut                  | 1.0.3               | toy-defenders-v1.0.3.jar                           | None                                     |
       | LC    | twilightforest       | 3.10.1013           | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LC    | vanillafix           | 1.0.10-150          | VanillaFix-1.0.10-150.jar                          | None                                     |
       | LC    | variedcommodities    | 1.12.2              | VariedCommodities_1.12.2(21nov19).jar              | None                                     |
       | LC    | waddles              | 0.6.0               | Waddles-1.12.2-0.6.0.jar                           | None                                     |
       | LC    | wolfarmor            | 3.4.1.1             | wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar      | None                                     |
       | LC    | youwinbutton         | 1.0.0               | youwinbutton-1.0.0.jar                             | None                                     |
       | LC    | phosphor-lighting    | 1.12.2-0.2.6        | Patchouli-1.0-20.jar                               | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LC    | additions            | 0.5.1               | Additions-0.5.1.jar                                | None                                     |
       | LC    | mysticallib          | 1.12.2-1.6.0        | mysticallib-1.12.2-1.6.0.jar                       | None                                     |
       | UD    | mclib_core           | 1.0.4               | minecraft.jar                                      | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      PerformantLoadingPlugin (performant-1.12.2-1.10.jar)
                                        
                                      PhosphorFMLLoadingPlugin (Patchouli-1.0-20.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      McLib core mod (mclib-1.0.4-1.12.2.jar)
                                        mchorse.mclib.core.McLibCMClassTransformer
                                      NikkoriCorePlugin (NikkoriMOD_ver-1.7.1.jar)
                                        nikkoricore.asm.NikkoriCoreTranceformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
                                        
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.8141' Renderer: 'Intel(R) UHD Graphics 630'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Suspected Mods: Maelstrom Mod (mm)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 26.20.100.8141, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Lucky+Block+Omega.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
i use the latest forge 1.1.2.2 version and the latest maelstrom version

**Comment by miyo6032** [comment]
Sorry, there is a conflict with one of the mods - I don't know which one, but for now, you will have to find which other mod conflicts, and decide which one to use. It will be fixed in the next version.

**Comment by TerraCrafterMC** [comment]
k
