### ISSUE TITLE
[suggestion] gamestage compatibility

### ISSUE THREAD

**Issue by Biviho** [miyo6032/MaelstromMod#31]
it would be cool to implement a gamestage compatibility for invasions, so a modpack dev can have more control on how to start invasions.

A name for the gamestage could be for example: startmaelstrominvasion or canmaelstrominvade.

Some good config could be:
-if use the gamestage to trigger invasions (inasions will start after the stage is set, after the altready configurable time is passed)

**Comment by miyo6032** [comment]
Something that integrates into game stages will be coming in the next update.
