### ISSUE TITLE
I'm sorry that I don't know what the problem is. I can only provide Crash

### ISSUE THREAD

**Issue by mcmso** [miyo6032/MaelstromMod#32]
**Describe the bug**
I'm sorry that I don't know what the problem is. I can only provide Crash
https://paste.ubuntu.com/p/svNhSHKvGy/         https://paste.ubuntu.com/p/BkQXdBrC2f/

**To Reproduce**

**Forge Version and Maelstrom Mod Version**
forge14.23.5.2854 Maelstrom+Mod-0.4

**Comment by miyo6032** [comment]
One of these crashes has been fixed in the release I just put out a few minutes ago. Backup your world, try if that works. If not get back to me.

**Comment by mcmso** [comment]
> One of these crashes has been fixed in the release I just put out a few minutes ago. Backup your world, try if that works. If not get back to me.

The second Crash has been resolved,thanks.

**Comment by mcmso** [comment]
> One of these crashes has been fixed in the release I just put out a few minutes ago. Backup your world, try if that works. If not get back to me.

The second Crash has been resolved,thanks.

**Comment by mcmso** [comment]
> One of these crashes has been fixed in the release I just put out a few minutes ago. Backup your world, try if that works. If not get back to me.


The first Crash has also been fixed,thanks.
