### ISSUE TITLE
Seems to conflict with DungeonTactics

### ISSUE THREAD

**Issue by mcmso** [miyo6032/MaelstromMod#34]
**Describe the bug**
https://paste.ubuntu.com/p/Jy4nQJNy4G/

**To Reproduce**

**Forge Version and Maelstrom Mod Version**
Forge 14.23.5.2854     Maelstrom+Mod-0.4.1  DungeonTactics-1.12.2-0.16.9

**Comment by miyo6032** [comment]
I can probably fix this within a week or so. Thanks for reporting!

**Comment by dazadazu** [comment]
Same crash over here too :0 Really excited to see the new boss mechanics though.

**Comment by miyo6032** [comment]
Put out 0.4.2 - should be fixed in that version
