### ISSUE TITLE
[suggestion] Russian translation for mod

### ISSUE THREAD

**Issue by HollowHorizon** [miyo6032/MaelstromMod#35]
I create russian translation of the mod.

Here's the file.
[ru_ru.txt](https://github.com/miyo6032/MaelstromMod/files/7686738/ru_ru.txt)
(I upload it as .txt file, because .lang files not supported on github)

**Comment by barribob** [comment]
Thanks, I will try to remember to put it in at some point

**Comment by AlgorithmLX** [comment]
> I create russian translation of the mod.
> 
> Here's the file. [ru_ru.txt](https://github.com/miyo6032/MaelstromMod/files/7686738/ru_ru.txt) (I upload it as .txt file, because .lang files not supported on github)

Hollow, could he just Pull Request make
